doctrine:
    dbal:
        url: "%env(resolve:DATABASE_URL)%"

        # Server version: for MariaDB/MySQL set via DATABASE_SERVERVERSION in .env (see DATABASE_URL).
        # Example for PostgreSQL: server_version: '16'

        profiling_collect_backtrace: "%kernel.debug%"
    orm:
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        identity_generation_preferences:
            Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
        auto_mapping: true

        mappings:
            App\Common\Presentation\Entity:
                type: attribute
                is_bundle: false
                dir: "%kernel.project_dir%/src/Common/Presentation/Entity"
                prefix: 'App\Common\Presentation\Entity'

            App\Account\Domain\Entity:
                type: attribute
                is_bundle: false
                dir: "%kernel.project_dir%/src/Account/Domain/Entity"
                prefix: 'App\Account\Domain\Entity'

            App\Organization\Domain\Entity:
                type: attribute
                is_bundle: false
                dir: "%kernel.project_dir%/src/Organization/Domain/Entity"
                prefix: 'App\Organization\Domain\Entity'

            App\ChatBasedContentEditor\Domain\Entity:
                type: attribute
                is_bundle: false
                dir: "%kernel.project_dir%/src/ChatBasedContentEditor/Domain/Entity"
                prefix: 'App\ChatBasedContentEditor\Domain\Entity'

            App\ProjectMgmt\Domain\Entity:
                type: attribute
                is_bundle: false
                dir: "%kernel.project_dir%/src/ProjectMgmt/Domain/Entity"
                prefix: 'App\ProjectMgmt\Domain\Entity'

            App\WorkspaceMgmt\Domain\Entity:
                type: attribute
                is_bundle: false
                dir: "%kernel.project_dir%/src/WorkspaceMgmt/Domain/Entity"
                prefix: 'App\WorkspaceMgmt\Domain\Entity'

            App\PhotoBuilder\Domain\Entity:
                type: attribute
                is_bundle: false
                dir: "%kernel.project_dir%/src/PhotoBuilder/Domain/Entity"
                prefix: 'App\PhotoBuilder\Domain\Entity'

        controller_resolver:
            auto_mapping: false

when@prod:
    doctrine:
        orm:
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
