twig:
    file_name_pattern: "*.twig"

    paths:
        "src/Common/Presentation/Resources/templates": "common.presentation"
        "src/StaticPages/Presentation/Resources/templates": "static_pages.presentation"
        "src/Account/Presentation/Resources/templates": "account.presentation"
        "src/ChatBasedContentEditor/Presentation/Resources/templates": "chat_based_content_editor.presentation"
        "src/ProjectMgmt/Presentation/Resources/templates": "project_mgmt.presentation"
        "src/WorkspaceMgmt/Presentation/Resources/templates": "workspace_mgmt.presentation"
        "src/Organization/Presentation/Resources/templates": "organization.presentation"

when@test:
    twig:
        strict_variables: true
