# Redirect root to default locale
root_redirect:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /en/
        permanent: false

api_controllers:
    resource: "../src/**/Api/**/*Controller.php"
    type: attribute

presentation_controllers:
    resource: "../src/**/Presentation/**/*Controller.php"
    type: attribute
    prefix: /{_locale}
    requirements:
        _locale: en|de
    defaults:
        _locale: en

shared:
    resource: "@SharedBundle/config/routes.yaml"

webui:
    resource: "@WebuiBundle/config/routes.yaml"
